### PR TITLE
Add gpg key id.

### PR DESCRIPTION
**Pull request by pstankie**
EF issue: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3684#note_1433269

### CODE REVIEW

**Review by wba2hi — APPROVED** [review]
LGTM

Additional Notes: (maybe obvious, but for me as somebody with no experience with GPG it wasn't)
- KEY_ID must be of the corresponding signing subkey
- KEY_ID must be in short form (last 8 chars of key)

**Comment by pstankie** [comment]
Actually, key id length is 17 https://keyserver.ubuntu.com/pks/lookup?search=059BD97D6B860B08&fingerprint=on&op=index 
If that doesn't work we can setup variable (?)

**Comment by wba2hi** [comment]
> Actually, key id length is 17 https://keyserver.ubuntu.com/pks/lookup?search=059BD97D6B860B08&fingerprint=on&op=index If that doesn't work we can setup variable (?)

Sorry, that maybe was a bit confusing. The key id length itself does not matter.
 
It only matters that the secret which is exposed here uses the short form, so the last 8 chars :) When I tried it with the full length key id the gradle build failed because it explicitely wanted to have the short version.  

See the build here for comparison: https://pipelinesghubeus6.actions.githubusercontent.com/jHbhpd0jty1Hpof85CEptK1oO87frIUJ1QK31h200mlfaxtYTh/_apis/pipelines/1/runs/42/signedlogcontent/2?urlExpires=2023-11-29T08%3A31%3A37.0240824Z&urlSigningMethod=HMACV1&urlSignature=Ckjr8wtfOiXgbn%2FSSfUHUpKS%2FQyWgS9vtRu7HJtbbXc%3D

It shows the following line: 
```
2023-11-28T12:33:58.2378175Z 2023-11-28T12:33:58.116+0000 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.IllegalStateException: The key ID must be in a valid form (eg 00B5050F or 0x00B5050F), given value: ***
```

Working link: https://github.com/boschglobal/kuksa-android-sdk/actions/runs/7018773710/job/19094859366

Edit: We probably also can simply truncate it from our side, so maybe not that important :)

**Comment by eclipsewebmaster** [comment]
Yes, I would suggest you truncate the key. The actual key_id, generated by gpg2 has the length stored in our vault and corresponds to key id stored in keyserver and changing that on our side would be inconsistent and insecure.

**Review by heurtematte — APPROVED** [review]

**Comment by pstankie** [comment]
changes are live

**Comment by pstankie** [comment]
changes are live

**Pull request merged**
