### PR TITLE
Initial branch protection rules for main branch in kuksa-android-sdk

### PR DESCRIPTION
**Pull request by SebastianSchildt**
This tries to enable branch protection for kuksa-android-sdk

### CODE REVIEW

**Comment by netomi** [comment]
In case you dont know, there is also a playground here: https://eclipse-kuksa.github.io/.eclipsefdn/playground/

where you can test out snippets before committing them to see the effect of snippets taking the default values into account.

**Comment by netomi** [comment]
Looks like that:

image

**Comment by SebastianSchildt** [comment]
@netomi  saw the playground, are you referring to that we might set some values explicitly that are already in default configuration? That for us just shows we made a conscious choice here (that will stay even if defaults are changed)

Or is there anything specific wrong with this PR that prevents merge? We _are_ new to this, basically we are taking a long hard look at he configs and the playground and try to "guess" what we want/need

**Comment by netomi** [comment]
If do make this setting to ensure that it gets not changed when the default config changes then its perfectly fine. You can also add comments in jsonnet to indicate the reasoning about things if you want.

In general, we would never change the default config in a way that projects would suddenly have different settings. The process when doing a necessary change in the default config is always do a reimport of all projects with the current live settings and update the configuration hosted in the .eclipsefdn repo. This process will not change.

Some projects wanted to have a minimal configuration, i.e. only specify the settings that are required, that is also the reason we added the canonical view to be able to see unnecessary settings. But there are also good reasons to just express what you want as a rule. Its perfectly fine for me.

**Comment by netomi** [comment]
Actually I forgot about this PR, for things like that we usually require some approval from a project lead or at least a fellow committer. Can you ask one of your colleagues to approve that? I can then quickly merge and apply it.

**Comment by SebastianSchildt** [comment]
> Actually I forgot about this PR, for things like that we usually require some approval from a project lead or at least a fellow committer. Can you ask one of your colleagues to approve that? I can then quickly merge and apply it.

@lukasmittag @eriksven

**Comment by netomi** [comment]
> Or is there anything specific wrong with this PR that prevents merge? We _are_ new to this, basically we are taking a long hard look at he configs and the playground and try to "guess" what we want/need

no the settings that you came up with a perfectly reasonable and a good start imho.

**Review by netomi — APPROVED** [review]

**Review by lukasmittag — APPROVED** [review]
LGTM

**Comment by netomi** [comment]
change has been applied.

**Pull request merged**
